[project]
name = "garden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "docker>=6.0.0",
    "esoreader>=1.2.3",
    "geopandas>=1.1.1",
    "html5lib>=1.1",
    "lxml>=6.0.0",
    "matplotlib>=3.10.3",
    "requests>=2.32.4",
    "selenium>=4.34.0",
    "tqdm>=4.67.1",
]
